sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Table\CreateTable.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Table\CreateIndex.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Table\CreateAdmin.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\CapNhatThanhTien.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\CMND.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\DatPhongMotHoaDon.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\DonDatPhong.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\Email.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\NgayBatDau.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\NgayDat.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\SoDienThoai.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Trigger\TenDangNhap.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Proc\BaoCaoDoanhThu.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Proc\BaoCaoDoanhThuNam.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Proc\ThemHoaDon.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Proc\TimPhongTrongTheoNgay.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Proc\TimKhachSan.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\KhachHang.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\KhachSan.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\LoaiPhong.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\Phong.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\TrangThaiPhong.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\DatPhong.sql
sqlcmd -E -S (localdb)\QLKS -i C:\Users\root\Desktop\Tony\CSDL\db\csld_nc\Data\HoaDon.sql
set /p delExit=Press the ENTER key to exit...: